<?php

namespace Kunstmaan\ApiBundle;

use Kunstmaan\ApiBundle\Schema\ApiSchema;
use Symfony\Component\DependencyInjection\Alias;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Definition;
use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class KunstmaanApiBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $apiDefiniton = new Definition(ApiSchema::class);
        $apiDefiniton->addMethodCall('initialize');
        $apiDefiniton->setArguments([new Reference('service_container')]);
        $container->setDefinition('graphql.schema', $apiDefiniton);

        $schemaAlias = new Alias('graphql.schema');
        $container->setAlias('kunstmaan_api.graphql.schema', $schemaAlias);
    }
}
